[package]
name = "Agnus"
version = "0.1.0"
edition = "2021"
build = "build.rs"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# Control + A, c リズミカルにするとqemuが終了できる

[dependencies]
riscv = "0.11.1"
riscv-rt = "0.12.2"
riscv-rt-macros = "0.2.1"